name: Greeting on variable day
on:
  push
env:
  DAY_OF_WEEK: Monday
  a: b
  First_name: Gagandeep   ## Low priority
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      First_name: Mark  ## Medium priority
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Eric  ## High priority
